# Generated by Django 5.1.7 on 2025-08-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backgroundColor',
            field=models.CharField(default='F43F5E', max_length=6),
        ),
    ]
