# Generated by Django 5.1.7 on 2025-08-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_backgroundcolor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='backgroundColor',
            new_name='background_color',
        ),
    ]
