# Generated by Django 5.1.7 on 2025-09-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='karma',
            field=models.IntegerField(default=0),
        ),
    ]
