# Generated by Django 5.1.7 on 2025-08-22 17:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('topic', models.CharField(choices=[('GAMING', 'Gaming & Entertainment'), ('TECH', 'Technology & Science'), ('SPORTS', 'Sports & Fitness'), ('MUSIC', 'Music & Arts'), ('NEWS', 'News & Politics'), ('TRAVEL', 'Travel & Holidays')], default='GAMING', max_length=20)),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
