# Generated by Django 5.1.7 on 2025-08-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='background_color',
            field=models.CharField(default='F43F5E', max_length=6),
        ),
    ]
