# Generated by Django 5.1.7 on 2025-08-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
