# Generated by Django 5.1.7 on 2025-08-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_community_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='member_count',
            field=models.IntegerField(default=1),
        ),
    ]
