# Generated by Django 5.1.7 on 2025-09-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_communitymemberships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='topic',
            field=models.CharField(choices=[('GAMING', 'Gaming & Entertainment'), ('TECH', 'Technology & Science'), ('SPORTS', 'Sports & Fitness'), ('MUSIC', 'Music & Arts'), ('NEWS', 'News & Politics'), ('TRAVEL', 'Travel & Holidays'), ('ANIMALS', 'Pets & Animals')], default='GAMING', max_length=20),
        ),
    ]
